spring:
    profiles:
        active: local
        
server:
    port: 25001
    
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mappers/*.xml
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/test
    username: 1234
    password: 1234
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    max-total: 10
    max-idle: 5

wesocket:
  port: 8888
  path: /websocket
